# permissions for end users to view frigates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: frigate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
  name: frigate-viewer-role
rules:
- apiGroups:
  - ship.my.domain
  resources:
  - frigates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ship.my.domain
  resources:
  - frigates/status
  verbs:
  - get
