apiVersion: ship.my.domain/v1beta1
kind: Frigate
metadata:
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate-sample
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test
  name: frigate-sample
spec:
  # TODO(user): Add fields here
